import { useRef } from "react";
import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

import type { RouterOutputs } from "~/utils/api";
import { api } from "~/utils/api";
import { LoadingPage, LoadingSpinner } from "~/components/loading";
import { toast } from "react-hot-toast";

dayjs.extend(relativeTime);

const Avatar = ({
    src,
    username,
}: {
    src: string;
    username?: null | string;
}) => {
    if (username) {
        return (
            <Link href={`/@${username}`}>
                <Image
                    src={src}
                    alt={`@${username}'s profile image`}
                    className="h-14 w-14 rounded-full"
                    width={56}
                    height={56}
                />
            </Link>
        );
    }
    return (
        <Image
            src={src}
            alt="Profile image"
            className="h-14 w-14 rounded-full"
            width={56}
            height={56}
        />
    );
};

const CreatePostWizard = () => {
    const { user, isSignedIn } = useUser();
    const input = useRef<null | HTMLInputElement>(null);

    const ctx = api.useContext();

    const { mutate, isLoading } = api.posts.create.useMutation({
        onSuccess() {
            if (!input.current) return;
            input.current.value = "";
            void ctx.posts.getAll.invalidate();
        },
        onError(e) {
            const errorMessage = e.data?.zodError?.fieldErrors.content;
            if (errorMessage) {
                for (const error of errorMessage) {
                    toast.error(error);
                }
            } else if (e.message === "TOO_MANY_REQUESTS") {
                toast.error("You can only post twice a minute, chill out.");
            } else {
                toast.error("Failed to post! Please try again later.");
            }
        },
    });

    if (!isSignedIn) return null;

    return (
        <form
            className="flex w-full items-center gap-3"
            onSubmit={(e) => {
                e.preventDefault();
                if (!input.current) return;
                mutate({
                    content: input.current.value,
                });
            }}
        >
            <Avatar src={user.profileImageUrl} username={user.username} />
            <input
                className="grow bg-transparent outline-none"
                placeholder="Emojis"
                type="text"
                ref={input}
                disabled={isLoading}
            />
            {!isLoading && (
                <input className="cursor-pointer" type="submit" value="Post" />
            )}
            {isLoading && <LoadingSpinner size={20} />}
        </form>
    );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = ({ post, author }: PostWithUser) => {
    return (
        <div className="flex w-full gap-3 border-b border-slate-400 p-4">
            <Avatar src={author.profileImageUrl} username={author.username} />
            <div className="flex flex-col">
                <div className="flex gap-1 text-slate-300">
                    <Link href={`/@${author.username}`}>
                        <span>{`@${author.username}`}</span>
                    </Link>
                    <span>·</span>
                    <Link href={`/post/${post.id}`}>
                        <span className="font-thin">
                            {dayjs(post.createdAt).fromNow()}
                        </span>
                    </Link>
                </div>
                <span className="text-2xl">{post.content}</span>
            </div>
        </div>
    );
};

const Feed = () => {
    const { data: posts, isLoading, isError } = api.posts.getAll.useQuery();

    if (isLoading) return <LoadingPage />;

    if (isError) return <div>Woops!</div>;

    return (
        <ul>
            {posts.map(({ post, author }) => (
                <li key={post.id}>
                    <PostView post={post} author={author} />
                </li>
            ))}
        </ul>
    );
};

const Home: NextPage = () => {
    api.posts.getAll.useQuery();

    const { isSignedIn, isLoaded: isUserLoaded } = useUser();

    if (!isUserLoaded) return <LoadingPage />;

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-screen justify-center">
                <div className="h-fit min-h-full w-full border-x border-slate-400 md:max-w-2xl">
                    <header className="flex border-b border-slate-400 p-4">
                        {!isSignedIn && (
                            <div className="flex justify-center">
                                <SignInButton />
                            </div>
                        )}
                        {!!isSignedIn && <CreatePostWizard />}
                    </header>
                    <Feed />
                </div>
            </main>
        </>
    );
};

export default Home;

