import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
    const { data: posts = [] } = api.posts.getAll.useQuery();
    const { user } = useUser();

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                {!user && <SignInButton />}
                {!!user && <SignOutButton />}
                <ul>
                    {posts.map((post) => (
                        <li key={post.id}>{post.content}</li>
                    ))}
                </ul>
            </main>
        </>
    );
};

export default Home;

